__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  '../base/dataloader.yml',
  '../base/optimizer.yml',
  '../base/deimv2.yml',
]

output_dir: ./outputs/deimv2_anime_finetune

num_classes: 1
remap_mscoco_category: False
epoches: 30
flat_epoch: 15
no_aug_epoch: 6

optimizer:
  params:
    -
      # except norm/bn/bias in self.dinov3
      params: '^(?=.*.dinov3)(?!.*(?:norm|bn|bias)).*$'
      lr: 0.000005
    -
      # including all norm/bn/bias in self.dinov3
      params: '^(?=.*.dinov3)(?=.*(?:norm|bn|bias)).*$'
      lr: 0.000005
      weight_decay: 0.
    -
      # including all norm/bn/bias except for self.dinov3
      params: '^(?=.*(?:sta|encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0001

ema:
  decay: 0.99
  warmups: 200

lr_warmup_scheduler:
  warmup_duration: 250

train_dataloader:
  total_batch_size: 64
  dataset:
    type: CocoDetection
    img_folder: dataset/images
    ann_file: dataset/train_annotations.json
    transforms:
      ops:
        - {type: Mosaic, output_size: 320, rotation_range: 10, translation_range: [0.1, 0.1], scaling_range: [0.6, 1.4],
           probability: 0.7, fill_value: 0, use_cache: True, max_cached_images: 50, random_pop: True}
        - {type: RandomPhotometricDistort, p: 0.3}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.5}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        epoch: [2, 15, 24]
  collate_fn:
    mixup_prob: 0.15
    base_size_repeat: 3
    mixup_epochs: [2, 10]
    stop_epoch: 24
    copyblend_epochs: [2, 24]

val_dataloader:
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [640, 640]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}

DEIMCriterion:
  matcher:
    matcher_change_epoch: 20