__include__: [
  '../dataset/anime_detection.yml', 
  '../runtime.yml',
  '../base/dataloader.yml',
  '../base/optimizer.yml',
  '../base/deimv2.yml',
]

output_dir: ./outputs/deimv2_dinov3_l_anime

DEIM:
  backbone: DINOv3STAs

DINOv3STAs:
  name: dinov3_vits16
  weights_path: ./ckpts/dinov3_vits16_pretrain_lvd1689m-08c60483.pth
  interaction_indexes: [5,8,11]
  finetune: False  
  conv_inplane: 32
  hidden_dim: 224

HybridEncoder:
  in_channels: [224, 224, 224]
  hidden_dim: 224
  dim_feedforward: 896

DEIMTransformer:
  feat_channels: [224, 224, 224]
  hidden_dim: 224
  num_layers: 4
  eval_idx: -1
  dim_feedforward: 1792
  num_classes: 1 

epoches: 16 

lrsheduler: flatcosine
lr_gamma: 0.5
warmup_iter: 1000 
flat_epoch: 8        
no_aug_epoch: 4      

optimizer:
  type: AdamW
  params: 
    - params: '^(?=.*(?:sta|encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.
    - params: '^(?=.*(?:sta|encoder|decoder))(?!.*(?:norm|bn|bias)).*$'
      weight_decay: 0.000125
  lr: 0.00025 
  betas: [0.9, 0.999]

train_dataloader: 
  total_batch_size: 16
  num_workers: 4     
  dataset: 
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: SanitizeBoundingBoxes, min_size: 4}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640]}
        - {type: SanitizeBoundingBoxes, min_size: 4}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy: 
        name: stop_epoch
        epoch: 12 
        ops: ['RandomPhotometricDistort', 'RandomZoomOut']

  collate_fn:
    base_size: 640
    base_size_repeat: 1 
    with_expand: False 
    stop_epoch: 12 

val_dataloader:
  total_batch_size: 16
  num_workers: 4     
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [640, 640]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
        
DEIMCriterion:
  num_classes: 1
  matcher:
    matcher_change_epoch: 11